import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // generated by `supabase gen types typescript` — never hand-edited
    'types/database.types.ts',
    // maplibre's worker, copied from node_modules by scripts/copy-maplibre-worker.mjs
    'public/maplibre/**',
  ]),
  {
    rules: {
      quotes: ['error', 'single', { avoidEscape: false }],
      'jsx-quotes': ['error', 'prefer-single'],
    },
  },
]);

export default eslintConfig
